[versions]
xp = "${xpVersion}"

[libraries]
xp-core-api = { module = "com.enonic.xp:core-api", version.ref = "xp" }
xp-portal-api = { module = "com.enonic.xp:portal-api", version.ref = "xp" }
xp-lib-context = { module = "com.enonic.xp:lib-context", version.ref = "xp" }
xp-lib-portal = { module = "com.enonic.xp:lib-portal", version.ref = "xp" }

[plugins]
enonic-xp-app = { id = "com.enonic.xp.app", version = "4.0.0-A2" }
